/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var dashcodePartSpecs = {
    "aspectLock": { "subviewsTransitions": [{ "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }, { "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }], "view": "DC.StackLayout" },
    "autodone": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "showMain", "rightImageWidth": 5, "text": "done", "view": "DC.View" },
    "autoGenerate": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "auto", "rightImageWidth": 5, "text": "auto", "view": "DC.View" },
    "doneSave": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "showFront", "rightImageWidth": 5, "text": "done", "view": "DC.View" },
    "download": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "versionDownload", "rightImageWidth": 5, "text": "download", "view": "DC.View" },
    "example": { "text": "example", "view": "DC.Text" },
    "explanation": { "text": "explanation", "view": "DC.Text" },
    "iaian7com": { "text": "iaian7com", "view": "DC.Text" },
    "image": { "view": "DC.ImageLayout" },
    "info": { "backgroundStyle": "black", "creationFunction": "CreateInfoButton", "foregroundStyle": "white", "frontID": "front", "onclick": "showBack", "view": "DC.View" },
    "InputBackground": { "creationFunction": "CreateShape", "leftImageWidth": 5, "rightImageWidth": 5 },
    "label": { "text": "Item", "view": "DC.Text" },
    "labelScale": { "text": "Item", "view": "DC.Text" },
    "limits": { "creationFunction": "CreatePopupButton", "leftImageWidth": 5, "onchange": "updateLimit", "options": [["no limit", "none"], ["integer", "1"], ["base 2", "2", true], ["base 4", "4"], ["base 5", "5"], ["base 6", "6"], ["base 8", "8"], ["base 10", "10"], ["base 12", "12"], ["base 16", "16"]], "rightImageWidth": 16, "view": "DC.View" },
    "new": { "text": "new", "view": "DC.Text" },
    "newVersion": { "text": "newVersion", "view": "DC.Text" },
    "presets": { "creationFunction": "CreatePopupButton", "leftImageWidth": 5, "name": "presets", "onchange": "updatePreset", "options": ["presets", ["HD 1080p", "1920x1080"], ["HD 720p", "1280x720"], ["HD 480p", "852x480"], ["SD NTSC", "720x480"], ["SD PAL", "720x576"], ["Apple iFrame", "960x540"], ["Apple iOS", "320x480"], ["Apple iOS Retina", "640x960"], ["Apple iPad", "1024x768"], ["Microsoft WP7", "480x800"], ["Microsoft Surface", "1024x768"], ["Microsoft Surface 2", "1920x1080"], ["Desktop Fullscreen", "1600x1200"], ["Desktop Widescreen", "1920x1200"], ["Film 1.85", "2220x1200"], ["Film 2.35", "2820x1200"]], "rightImageWidth": 16, "view": "DC.View" },
    "ratioList": { "allowsEmptySelection": true, "dataArray": ["Item 1", "Item 2", "Item 3"], "dataSourceName": "listData", "labelElementId": "label", "listStyle": "List.EDGE_TO_EDGE", "sampleRows": 3, "selectionEnabled": true, "useDataSource": true, "view": "DC.List" },
    "scrollArea": { "autoHideScrollbars": true, "creationFunction": "CreateScrollArea", "hasVerticalScrollbar": true, "scrollbarDivSize": 18, "scrollbarMargin": 6, "spacing": -18, "view": "DC.View" },
    "skip": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "showMain", "rightImageWidth": 5, "text": "skip", "view": "DC.View" },
    "sliderBackground": { "creationFunction": "CreateShape", "leftImageWidth": 5, "rightImageWidth": 5 },
    "stack": { "subviewsTransitions": [{ "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }, { "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }, { "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }], "view": "DC.StackLayout" },
    "swap": { "creationFunction": "CreateShape", "view": "DC.View" },
    "text": { "text": "©2012 John Einselen, Vectorform LLC", "view": "DC.Text" },
    "x1": { "text": "x", "view": "DC.Text" },
    "x2": { "text": "%", "view": "DC.Text" },
    "x3": { "text": "x", "view": "DC.Text" }
};




