/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var localizedStrings = {
    "auto": "auto",
    "done": "done",
    "download": "download",
    "example": "(example: WMV codecs require base 2)",
    "explanation": "Click the Ratio icon to find alternate resolutions defined by the base limit above.\n\nUse arrow keys to quickly adjust values, and hold the shift key for multiples of ten.",
    "explanation1": "Click the Ratio icon to find alternate resolutions defined by the base limit.\n(example: WMV codec requires base 2)\nUse arrow keys to quickly adjust values, and hold the shift key for multiples of ten.",
    "iaian7com": "For more, visit iaian7.com",
    "new": "new update available!",
    "newVersion": "version number\nversion description",
    "skip": "skip version",
    "x": "×"
};



