/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var localizedStrings = {
    "auto": "auto",
    "done": "done",
    "download": "download",
    "explanation": "Simultaneous match limits affect only auto generate and the scale slider (some video codecs require base 2 resolutions).\n\nUse the arrow keys to quickly adjust values interactively. Hold the shift key to adjust in multiples of ten.",
    "iaian7com": "For more information, please visit iaian7.com/dashboard/ratio",
    "new": "new version available",
    "newVersion": "version number\nversion description",
    "skip": "skip version"
};
